package gin_app

import (
	c "context"
	"fmt"
	app "github.com/harishb2k/gox-app"
	"github.com/harishb2k/gox-base"
	"github.com/harishb2k/gox-base/serialization"
	"github.com/stretchr/testify/assert"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"testing"
)

type getTestAutoGenerated struct {
	Input string `json:"input"`
	Age   int    `json:"age"`
}

func TestGetRequest(t *testing.T) {
	router := NewGinApp(app.ApplicationConfig{},gox.NewNoOpCrossFunction()).(*ginApp)

	ts := httptest.NewServer(router.engine)
	defer ts.Close()

	router.GET(
		app.NewRouterConfigBuilder("example").
			WithPath("/ping/:name").
			WithHandlerFunc(func(ctx c.Context, request app.Request, response app.Response, requestContext app.RequestContext) {
				name, _ := request.GetPathParam("name")
				data := getTestAutoGenerated{
					Input: name,
					Age:   10,
				}
				response.Done(app.NewResponseDataBuilder().WithObjectBody(data).Build())
			}).
			Build(),
	)

	// Make a GET call
	resp, err := http.Get(fmt.Sprintf("%s/ping/user_1", ts.URL))

	// Do basic check that we got 200 and correct content-type
	assert.NoError(t, err, "failed to make http call to /ping")
	assert.Equal(t, 200, resp.StatusCode)
	val, ok := resp.Header["Content-Type"]
	assert.True(t, ok)
	assert.Equal(t, app.ContentTypeJson.String(), val[0])

	// Check body
	data, err := ioutil.ReadAll(resp.Body)
	assert.NoError(t, err, "failed to read body")

	obj := getTestAutoGenerated{}
	err = serialization.JsonBytesToObject(data, &obj)
	assert.NoError(t, err, "failed to parse body")
	assert.Equal(t, "user_1", obj.Input)
	assert.Equal(t, 10, obj.Age)
}
